### ISSUE TITLE
MainForm.cs does not load correctly in the Designer (on VS 2012)

### ISSUE THREAD

**Issue by jhominal** [cliss/BindingFlagsTester#1]
When I load the `MainForm.cs` file in the designer, it does not load correctly:

![image](https://cloud.githubusercontent.com/assets/96824/8797039/4db3fa2c-2f99-11e5-88e0-023a42129980.png)

However, if I replace the following line in `BindingFlagsTester.csproj`:

``` xml
    <Compile Include="MainForm.Designer.cs" />
```

With the following block:

``` xml
    <Compile Include="MainForm.Designer.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
```

Then the designer loads the form correctly:
![image](https://cloud.githubusercontent.com/assets/96824/8797143/d4f12b4a-2f99-11e5-9e87-fa6f58f22e32.png)

Can you observe the same issue?

**Comment by cliss** [comment]
The project is written against Visual Studio 2013; I suspect that's the problem.

That said, if you were to create a new WinForms project, and add all the requisite files into that project, I presume it would work just fine.
